from pathlib import Path

path = Path('app.py')
text = path.read_text(encoding='utf-8')

old_uploads = '''            col_ef1, col_ef2, col_ef3 = st.columns(3)\n            with col_ef1:\n                arq_despesa_ef = st.file_uploader(\n                    'Planilha Despesa', type=['xls', 'xlsx'], key='ef242_despesa'\n                )\n            with col_ef2:\n                arq_fornecedor_ef = st.file_uploader(\n                    'Planilha Fornecedor', type=['xls', 'xlsx'], key='ef242_fornecedor'\n                )\n            with col_ef3:\n                arq_recebido_ef = st.file_uploader(\n                    'Planilha Recebido', type=['xls', 'xlsx'], key='ef242_recebido'\n                )\n'''
new_uploads = '''            col_ef1, col_ef2, col_ef3 = st.columns(3)\n            with col_ef1:\n                arq_despesa_ef = st.file_uploader(\n                    'Planilha Despesa', type=['xls', 'xlsx'], key='ef242_despesa'\n                )\n                download_despesa_ef = st.empty()\n            with col_ef2:\n                arq_fornecedor_ef = st.file_uploader(\n                    'Planilha Fornecedor', type=['xls', 'xlsx'], key='ef242_fornecedor'\n                )\n                download_fornecedor_ef = st.empty()\n            with col_ef3:\n                arq_recebido_ef = st.file_uploader(\n                    'Planilha Recebido', type=['xls', 'xlsx'], key='ef242_recebido'\n                )\n                download_recebido_ef = st.empty()\n'''
if old_uploads not in text:
    raise SystemExit('Bloco de uploads da 242 não encontrado')
text = text.replace(old_uploads, new_uploads, 1)

old_download = '''                    arquivo_ef = gerar_modelo_dominio_eletro_forte(\n                        despesas_ef, fornecedores_ef, recebidos_ef\n                    )\n                    st.download_button(\n                        'Baixar Modelo Domínio — Eletro Forte', data=arquivo_ef,\n                        file_name=f'ELETRO_FORTE_242_{int(ano_ef)}.xlsx',\n                        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',\n                        use_container_width=True, key='ef242_download',\n                    )\n'''
new_download = '''                    # Cada relatório da 242 gera seu próprio Modelo Domínio.\n                    # A ordem original das linhas é preservada e as colunas permanecem\n                    # exatamente em DATA, DÉBITO, CRÉDITO, VALOR e HISTÓRICO.\n                    mime_excel_ef = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'\n                    if despesas_ef is not None and not despesas_ef.empty:\n                        arquivo_despesa_ef = gerar_modelo_dominio_eletro_forte(\n                            despesas_ef, {}, {}\n                        )\n                        download_despesa_ef.download_button(\n                            'Baixar Despesa · Modelo Domínio',\n                            data=arquivo_despesa_ef,\n                            file_name=f'ELETRO_FORTE_242_DESPESA_{int(ano_ef)}.xlsx',\n                            mime=mime_excel_ef,\n                            use_container_width=True,\n                            key='ef242_download_despesa',\n                        )\n                    if fornecedores_ef:\n                        arquivo_fornecedor_ef = gerar_modelo_dominio_eletro_forte(\n                            None, fornecedores_ef, {}\n                        )\n                        download_fornecedor_ef.download_button(\n                            'Baixar Fornecedor · Modelo Domínio',\n                            data=arquivo_fornecedor_ef,\n                            file_name=f'ELETRO_FORTE_242_FORNECEDOR_{int(ano_ef)}.xlsx',\n                            mime=mime_excel_ef,\n                            use_container_width=True,\n                            key='ef242_download_fornecedor',\n                        )\n                    if recebidos_ef:\n                        arquivo_recebido_ef = gerar_modelo_dominio_eletro_forte(\n                            None, {}, recebidos_ef\n                        )\n                        download_recebido_ef.download_button(\n                            'Baixar Recebido · Modelo Domínio',\n                            data=arquivo_recebido_ef,\n                            file_name=f'ELETRO_FORTE_242_RECEBIDO_{int(ano_ef)}.xlsx',\n                            mime=mime_excel_ef,\n                            use_container_width=True,\n                            key='ef242_download_recebido',\n                        )\n'''
if old_download not in text:
    raise SystemExit('Download combinado da 242 não encontrado')
text = text.replace(old_download, new_download, 1)
path.write_text(text, encoding='utf-8')
