from pathlib import Path

path = Path('app.py')
text = path.read_text(encoding='utf-8')
needle = """        termo_normalizado = _normalizar_busca_empresa(termo_busca_empresas)\n\n        if not termo_normalizado:\n"""
replacement = """        termo_normalizado = _normalizar_busca_empresa(termo_busca_empresas)\n\n        st.markdown(\n            \"\"\"\n            <style>\n            [class*=\"st-key-org_resultado_empresa_\"] button,\n            [class*=\"st-key-org_empresa_ativa_\"] button {\n                background: transparent !important;\n                border: 0 !important;\n                box-shadow: none !important;\n                padding: 0 !important;\n                min-height: auto !important;\n                height: auto !important;\n                border-radius: 0 !important;\n                justify-content: flex-start !important;\n            }\n            [class*=\"st-key-org_resultado_empresa_\"] button p,\n            [class*=\"st-key-org_empresa_ativa_\"] button p {\n                font-weight: 500 !important;\n                line-height: 1.45 !important;\n                margin: 0 !important;\n            }\n            [class*=\"st-key-org_resultado_empresa_\"] button:hover,\n            [class*=\"st-key-org_empresa_ativa_\"] button:hover,\n            [class*=\"st-key-org_resultado_empresa_\"] button:focus,\n            [class*=\"st-key-org_empresa_ativa_\"] button:focus {\n                background: transparent !important;\n                border: 0 !important;\n                box-shadow: none !important;\n            }\n            [class*=\"st-key-org_resultado_empresa_\"] button:hover p,\n            [class*=\"st-key-org_empresa_ativa_\"] button:hover p {\n                color: #06b6d4 !important;\n                text-decoration: underline !important;\n                text-underline-offset: 3px !important;\n            }\n            </style>\n            \"\"\",\n            unsafe_allow_html=True,\n        )\n\n        if not termo_normalizado:\n"""
if needle not in text:
    raise SystemExit('Trecho alvo não encontrado')
text = text.replace(needle, replacement, 1)
path.write_text(text, encoding='utf-8')
