from pathlib import Path

p = Path('razync/valean_625.py')
s = p.read_text(encoding='utf-8')
old = '''def _limpar_cpf_cnpj_historico(texto: str) -> str:\n    texto = str(texto or \"\")\n    padroes = [\n        r\"\\b(?:CPF|CNPJ)\\s*[:\\-]?\\s*(?:\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}|\\d{2}\\.?\\d{3}\\.?\\d{3}/?\\d{4}-?\\d{2}|\\d{11}|\\d{14})\\b\",\n        r\"(?<!\\d)(?:\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}|\\d{2}\\.?\\d{3}\\.?\\d{3}/?\\d{4}-?\\d{2}|\\d{11}|\\d{14})(?!\\d)\",\n    ]\n    for padrao in padroes:\n        texto = re.sub(padrao, \" \", texto, flags=re.I)\n    texto = re.sub(r\"\\b(?:CPF|CNPJ)\\b\\s*[:\\-]?\", \" \", texto, flags=re.I)\n    return re.sub(r\"\\s+\", \" \", texto).strip(\" -|;,:.\")\n'''
new = '''def _limpar_cpf_cnpj_historico(texto: str) -> str:\n    \"\"\"Remove CPF/CNPJ dos históricos da 625 sem apagar nomes úteis.\n\n    Trata os formatos reais dos extratos BB e Sicredi, inclusive documentos\n    sem máscara no meio da descrição.\n    \"\"\"\n    texto = str(texto or \"\")\n\n    # Documento com 11 ou 14 dígitos, com ou sem máscara.\n    doc = (\n        r\"(?:\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}\"\n        r\"|\\d{2}\\.?\\d{3}\\.?\\d{3}/?\\d{4}-?\\d{2}\"\n        r\"|\\d{11}|\\d{14})\"\n    )\n\n    # BB: em TED/PIX o CPF/CNPJ pode vir depois de banco/agência ou data/hora.\n    texto = re.sub(\n        rf\"(?<!\\d)\\d{{3}}\\s+\\d{{4}}\\s+(?={doc}(?!\\d))\",\n        \" \", texto, flags=re.I,\n    )\n    texto = re.sub(\n        rf\"(?<!\\d)\\d{{2}}/\\d{{2}}\\s+\\d{{2}}:\\d{{2}}\\s+(?={doc}(?!\\d))\",\n        \" \", texto, flags=re.I,\n    )\n\n    # Remove rótulo opcional e o próprio documento.\n    texto = re.sub(\n        rf\"\\b(?:CPF|CNPJ)\\b\\s*[:\\-]?\\s*(?={doc}(?!\\d))\",\n        \" \", texto, flags=re.I,\n    )\n    texto = re.sub(rf\"(?<!\\d){doc}(?!\\d)\", \" \", texto, flags=re.I)\n    texto = re.sub(r\"\\b(?:CPF|CNPJ)\\b\\s*[:\\-]?\", \" \", texto, flags=re.I)\n\n    return re.sub(r\"\\s+\", \" \", texto).strip(\" -|;,:.\")\n'''
if old not in s:
    raise SystemExit('função antiga não encontrada')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
