from pathlib import Path
p=Path('app.py')
s=p.read_text(encoding='utf-8')
needle='''    aba_operacoes, aba_base = st.tabs(["Organizar arquivos", "Base Inteligente"])\n\n    with aba_operacoes:\n        st.markdown("#### Extratos bancários → Modelo Domínio")'''
replacement='''    aba_operacoes, aba_base = st.tabs(["Organizar arquivos", "Base Inteligente"])\n\n    # A conferência genérica espera identificar o banco pelo conteúdo/estrutura da\n    # planilha. O arquivo da 625 é gerado em abas por banco; por isso, lemos a aba\n    # correspondente diretamente e devolvemos o quadro normalizado ao motor legado.\n    _ler_planilha_conf_legado_625 = globals().get("ler_planilha_organizada_conferencia")\n\n    def _ler_planilha_conferencia_625(file_bytes, banco_slug):\n        if banco_slug not in {"banco_brasil", "caixa", "sicredi"}:\n            return _ler_planilha_conf_legado_625(file_bytes, banco_slug)\n        nomes = {\n            "banco_brasil": ["Banco do Brasil", "Banco do Brasil · Conta 8"],\n            "caixa": ["Caixa", "Caixa · Conta 508"],\n            "sicredi": ["Sicredi", "Sicredi · Conta 3999"],\n        }\n        xls = pd.ExcelFile(io.BytesIO(file_bytes))\n        alvo = next((n for n in nomes[banco_slug] if n in xls.sheet_names), None)\n        if alvo is None:\n            # Compatibilidade com nomes de abas sanitizados/truncados.\n            termo = {"banco_brasil": "brasil", "caixa": "caixa", "sicredi": "sicredi"}[banco_slug]\n            alvo = next((n for n in xls.sheet_names if termo in normalizar_texto(n)), None)\n        if alvo is None:\n            return pd.DataFrame(), pd.DataFrame(), set()\n        df = pd.read_excel(io.BytesIO(file_bytes), sheet_name=alvo)\n        df.columns = [str(c).strip().upper() for c in df.columns]\n        if "DATA" not in df.columns or "VALOR" not in df.columns:\n            return pd.DataFrame(), pd.DataFrame(), set()\n        df["DATA"] = pd.to_datetime(df["DATA"], dayfirst=True, errors="coerce")\n        df["VALOR"] = pd.to_numeric(df["VALOR"], errors="coerce")\n        df = df.dropna(subset=["DATA", "VALOR"]).reset_index(drop=True)\n        return df, pd.DataFrame(), {banco_slug}\n\n    with aba_operacoes:\n        st.markdown("#### Extratos bancários → Modelo Domínio")'''
if needle not in s: raise SystemExit('bloco 625 não encontrado')
s=s.replace(needle,replacement,1)
needle2='''        renderizar_conferencia_autokraft(\n            "valean_625", bancos_config=configs,\n            rotulo_planilha="Planilha final organizada da empresa 625",\n        )'''
replacement2='''        _ler_planilha_conf_original_625 = globals().get("ler_planilha_organizada_conferencia")\n        try:\n            globals()["ler_planilha_organizada_conferencia"] = _ler_planilha_conferencia_625\n            renderizar_conferencia_autokraft(\n                "valean_625", bancos_config=configs,\n                rotulo_planilha="Planilha final organizada da empresa 625",\n            )\n        finally:\n            globals()["ler_planilha_organizada_conferencia"] = _ler_planilha_conf_original_625'''
if needle2 not in s: raise SystemExit('conferência 625 não encontrada')
s=s.replace(needle2,replacement2,1)
p.write_text(s,encoding='utf-8')
print('OK')