from pathlib import Path

path = Path('app.py')
s = path.read_text(encoding='utf-8')

old = '''        # Diferente de st.tabs: somente a ferramenta escolhida é executada.\n        # Isso evita chamadas ao Supabase e à conferência enquanto o usuário\n        # está apenas organizando os arquivos da 968.\n        modo_radani = st.radio(\n            'Ferramenta da 968',\n            ['Organizar arquivos', 'Base Inteligente', 'Conferência com extrato'],\n            horizontal=True,\n            label_visibility='collapsed',\n            key='radani_modo_ferramenta',\n        )\n\n        if modo_radani == 'Base Inteligente':\n'''
new = '''        # Navegação visual padronizada com as demais empresas, mantendo execução\n        # preguiçosa por trás para a 968 não voltar a ficar pesada.\n        st.markdown(\n            \"\"\"\n            <style>\n            [class*=\"st-key-radani_modo_ferramenta\"] > div:first-child {\n                gap: 1.2rem !important;\n                border-bottom: 1px solid rgba(73, 108, 132, .24) !important;\n                margin: .05rem 0 .62rem !important;\n            }\n            [class*=\"st-key-radani_modo_ferramenta\"] label {\n                min-height: 2.35rem !important;\n                padding: .42rem .08rem .5rem !important;\n                margin: 0 !important;\n                border-radius: 0 !important;\n                background: transparent !important;\n                border: 0 !important;\n                font-size: .78rem !important;\n                font-weight: 500 !important;\n                color: #91a2b2 !important;\n            }\n            [class*=\"st-key-radani_modo_ferramenta\"] label:has(input:checked) {\n                color: #f3f7fa !important;\n                box-shadow: inset 0 -2px 0 #20bee9 !important;\n            }\n            [class*=\"st-key-radani_modo_ferramenta\"] [data-testid=\"stMarkdownContainer\"] p {\n                font-size: .78rem !important;\n            }\n            [class*=\"st-key-radani_modo_ferramenta\"] input,\n            [class*=\"st-key-radani_modo_ferramenta\"] [data-testid=\"stWidgetLabel\"] {\n                display: none !important;\n            }\n            </style>\n            \"\"\",\n            unsafe_allow_html=True,\n        )\n        modo_radani = st.radio(\n            'Ferramenta da 968',\n            ['Organizar arquivos', 'Base Inteligente'],\n            horizontal=True,\n            label_visibility='collapsed',\n            key='radani_modo_ferramenta',\n        )\n\n        if modo_radani == 'Base Inteligente':\n'''
if old not in s:
    raise SystemExit('Bloco inicial da Radani não encontrado')
s = s.replace(old, new, 1)

old_branch = '''        elif modo_radani == 'Conferência com extrato':\n            st.caption(\n                'A conferência é carregada somente quando esta ferramenta está aberta, '\n                'sem pesar no organizador da 968.'\n            )\n            renderizar_conferencia_autokraft(\n                slug_radani,\n                bancos_config=[\n                    {'nome': 'Itaú', 'slug': 'itau'},\n                    {'nome': 'Bradesco', 'slug': 'bradesco'},\n                ]\n            )\n\n        else:\n'''
if old_branch not in s:
    raise SystemExit('Ramo de conferência da Radani não encontrado')
s = s.replace(old_branch, '''        else:\n''', 1)

anchor = '''            elif resultado_radani:\n                st.caption(\n                    'Os arquivos selecionados mudaram. Clique em Processar 968 para gerar um novo resultado.'\n                )\n\n    if st.session_state['empresa_organizador'] == 'up_pack':\n'''
replacement = '''            elif resultado_radani:\n                st.caption(\n                    'Os arquivos selecionados mudaram. Clique em Processar 968 para gerar um novo resultado.'\n                )\n\n            st.markdown(f'#### Conferência — {empresa_radani}')\n            abrir_conferencia_radani = st.checkbox(\n                'Abrir Conferência com o extrato',\n                value=False,\n                key='radani_abrir_conferencia',\n                help='A conferência fica dentro do Organizador como nas demais empresas, mas só carrega quando aberta para preservar a performance.'\n            )\n            if abrir_conferencia_radani:\n                renderizar_conferencia_autokraft(\n                    slug_radani,\n                    bancos_config=[\n                        {'nome': 'Itaú', 'slug': 'itau'},\n                        {'nome': 'Bradesco', 'slug': 'bradesco'},\n                    ]\n                )\n\n    if st.session_state['empresa_organizador'] == 'up_pack':\n'''
if anchor not in s:
    raise SystemExit('Âncora final da Radani não encontrada')
s = s.replace(anchor, replacement, 1)

path.write_text(s, encoding='utf-8')
